[build]
  functions = "netlify/functions"
  publish = "public"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/randomverse"
  to = "/.netlify/functions/randomverse"
  status = 200

[[redirects]]
  from = "/api/makespecificverse"
  to = "/.netlify/functions/makespecificverse"
  status = 200
